name: RPG
version: '${project.version}'
main: net.mineshock.rpg.RPG
api-version: '1.20'
commands:
  summonmob:
    description: summons custom mob
    usage: /summonmob <mobname> <level>
  test:
    description: test command
  questUpdate:
      description: updates quest stage
      usage: /questUpdate <questName> <stage>